<Box01>:
	spacing: 10
	padding: 10
	canvas:
		Color:
			rgb: 1, 1, 1
		Rectangle:
			size: self.size
			pos: self.pos
<BRed>:
	orientation: "vertical"
	spacing: 10
	padding: 10
	canvas:
		Color:
			rgb: 1, 0, 0
		Rectangle:
			size: self.size
			pos: self.pos
<BGreen>:
	spacing: 10
	padding: 10
	canvas:
		Color:
			rgb: 0, 1, 0
		Rectangle:
			size: self.size
			pos: self.pos
<BBlue>:
	spacing: 10
	padding: 10
	canvas:
		Color:
			rgb: 0, 0, 1
		Rectangle:
			size: self.size
			pos: self.pos
